# Generated by Django 4.1.3 on 2022-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_director_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(help_text='Descripcion de la pelicula', max_length=256),
        ),
    ]
